spring:
  application:
    name: java-backend-onboarding

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  header: Authorization
  secret-key: ${JWT_SECRET_KEY}
  refresh-secret-key: ${JWT_REFRESH_KEY}
